version: "3.1"

services:
  ticket-service:
    build: ./ticket-service # image
    container_name: tic-serv-cont
    ports:
      - "8000:8000"
    
  support-service:
    build: ./support-service # image
    container_name: sup-serv-cont
    ports:
      - "8001:8001"
  
  notification-service:
    build: ./notification-service # image
    container_name: noti-serv-cont
    ports:
      - "8002:8002"

  reporting-service:
    build: ./reporting-service # image
    container_name: rep-serv-cont
    ports:
      - "8003:8003"